"""PostgreSQL connections and explicit schema initialization."""

from __future__ import annotations

import os
from collections.abc import Iterator
from contextlib import contextmanager
from typing import Any, TypeAlias
from urllib.parse import unquote, urlparse

import psycopg
from psycopg.rows import dict_row


DatabaseRow: TypeAlias = dict[str, Any]
DatabaseConnection: TypeAlias = psycopg.Connection[DatabaseRow]


def get_database_url(variable_name: str = "DATABASE_URL") -> str:
    database_url = os.getenv(variable_name, "").strip()
    if not database_url:
        raise ValueError(f"{variable_name} 尚未配置")
    if urlparse(database_url).scheme not in {"postgresql", "postgres"}:
        raise ValueError(f"{variable_name} 必须是 PostgreSQL 连接地址")
    return database_url


def connect(database_url: str | None = None) -> DatabaseConnection:
    return psycopg.connect(
        database_url or get_database_url(),
        row_factory=dict_row,
        connect_timeout=10,
    )


@contextmanager
def open_database(database_url: str | None = None) -> Iterator[DatabaseConnection]:
    connection = connect(database_url)
    try:
        yield connection
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


SCHEMA_STATEMENTS = (
    """CREATE TABLE IF NOT EXISTS routes (
           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           code TEXT NOT NULL UNIQUE,
           name TEXT NOT NULL,
           origin_city_name TEXT NOT NULL,
           destination_city_name TEXT NOT NULL,
           total_distance_km INTEGER NOT NULL,
           geometry_json TEXT,
           is_active BOOLEAN NOT NULL DEFAULT TRUE
       )""",
    """CREATE TABLE IF NOT EXISTS cities (
           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           name TEXT NOT NULL UNIQUE,
           city_code TEXT NOT NULL UNIQUE,
           province TEXT NOT NULL,
           longitude DOUBLE PRECISION NOT NULL,
           latitude DOUBLE PRECISION NOT NULL,
           description TEXT,
           climate_description TEXT
       )""",
    """CREATE TABLE IF NOT EXISTS route_stations (
           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           route_id INTEGER NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
           city_id INTEGER NOT NULL REFERENCES cities(id) ON DELETE RESTRICT,
           station_order INTEGER NOT NULL,
           distance_from_origin_km DOUBLE PRECISION NOT NULL,
           station_name TEXT NOT NULL,
           longitude DOUBLE PRECISION NOT NULL,
           latitude DOUBLE PRECISION NOT NULL,
           UNIQUE(route_id, city_id),
           UNIQUE(route_id, station_order)
       )""",
    """CREATE TABLE IF NOT EXISTS weather_observations (
           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           city_id INTEGER NOT NULL REFERENCES cities(id) ON DELETE RESTRICT,
           observation_date TEXT NOT NULL,
           observed_at TEXT NOT NULL,
           temperature_c DOUBLE PRECISION NOT NULL,
           feels_like_c DOUBLE PRECISION,
           weather_text TEXT NOT NULL,
           weather_code INTEGER,
           humidity_percent INTEGER NOT NULL,
           wind_speed_ms DOUBLE PRECISION,
           wind_direction TEXT,
           precipitation_probability_percent INTEGER,
           visibility_km DOUBLE PRECISION,
           cloud_cover_percent INTEGER,
           source TEXT NOT NULL,
           UNIQUE(city_id, observation_date)
       )""",
    """CREATE TABLE IF NOT EXISTS air_quality_observations (
           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           weather_observation_id BIGINT NOT NULL UNIQUE
               REFERENCES weather_observations(id) ON DELETE CASCADE,
           city_id INTEGER NOT NULL REFERENCES cities(id) ON DELETE RESTRICT,
           aqi INTEGER NOT NULL,
           pm25_ug_m3 DOUBLE PRECISION,
           pm10_ug_m3 DOUBLE PRECISION,
           primary_pollutant TEXT
       )""",
    """CREATE TABLE IF NOT EXISTS atmosphere_analyses (
           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           weather_observation_id BIGINT NOT NULL UNIQUE
               REFERENCES weather_observations(id) ON DELETE CASCADE,
           city_id INTEGER NOT NULL REFERENCES cities(id) ON DELETE RESTRICT,
           stability_class TEXT NOT NULL,
           stability_level TEXT NOT NULL,
           period TEXT NOT NULL,
           wind_speed_ms DOUBLE PRECISION NOT NULL,
           cloud_cover_percent INTEGER NOT NULL,
           solar_elevation_deg DOUBLE PRECISION NOT NULL,
           insolation_category TEXT,
           confidence TEXT NOT NULL,
           method TEXT NOT NULL,
           explanation TEXT NOT NULL,
           calculation_version TEXT NOT NULL
       )""",
    """CREATE TABLE IF NOT EXISTS travel_reports (
           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           route_id INTEGER NOT NULL REFERENCES routes(id) ON DELETE RESTRICT,
           travel_date TEXT NOT NULL,
           content TEXT NOT NULL,
           model_name TEXT NOT NULL,
           prompt_hash TEXT NOT NULL,
           generated_at TEXT NOT NULL,
           source_snapshot_json TEXT NOT NULL,
           UNIQUE(route_id, travel_date)
       )""",
    """CREATE TABLE IF NOT EXISTS daily_update_runs (
           run_date TEXT PRIMARY KEY,
           trigger TEXT NOT NULL CHECK(trigger = 'cron'),
           status TEXT NOT NULL
               CHECK(status IN ('running', 'succeeded', 'partial', 'failed', 'skipped')),
           started_at TEXT NOT NULL,
           finished_at TEXT,
           weather_updated_count INTEGER NOT NULL DEFAULT 0,
           weather_failed_count INTEGER NOT NULL DEFAULT 0,
           advice_generated_count INTEGER NOT NULL DEFAULT 0,
           advice_failed_count INTEGER NOT NULL DEFAULT 0,
           error_summary TEXT
       )""",
    """CREATE TABLE IF NOT EXISTS operation_leases (
           lease_name TEXT PRIMARY KEY,
           owner_token TEXT NOT NULL,
           expires_at TIMESTAMPTZ NOT NULL
       )""",
    """CREATE INDEX IF NOT EXISTS idx_route_stations_route_order
       ON route_stations(route_id, station_order)""",
    """CREATE INDEX IF NOT EXISTS idx_weather_city_date
       ON weather_observations(city_id, observation_date DESC)""",
    """CREATE INDEX IF NOT EXISTS idx_travel_reports_route_date
       ON travel_reports(route_id, travel_date DESC)""",
)


def initialize_database(database_url: str | None = None) -> None:
    """Create the current schema. This is an explicit deployment operation."""
    with open_database(database_url) as connection:
        for statement in SCHEMA_STATEMENTS:
            connection.execute(statement)


def require_test_database_url(database_url: str | None = None) -> str:
    """Reject cleanup unless the target database name visibly ends in _test."""
    selected_url = database_url or get_database_url("TEST_DATABASE_URL")
    database_name = unquote(urlparse(selected_url).path).removeprefix("/")
    if not database_name.endswith("_test"):
        raise ValueError("TEST_DATABASE_URL 的数据库名必须以 _test 结尾")
    return selected_url


def reset_test_database(database_url: str | None = None) -> None:
    selected_url = require_test_database_url(database_url)
    with open_database(selected_url) as connection:
        connection.execute(
            """TRUNCATE TABLE
                   operation_leases, daily_update_runs, atmosphere_analyses,
                   air_quality_observations, travel_reports, weather_observations,
                   route_stations, cities, routes
               RESTART IDENTITY CASCADE"""
        )


def initialize_database_from_environment() -> None:
    """Initialize and seed through the non-pooler migration connection."""
    from .seed import seed_database

    migration_url = get_database_url("DATABASE_MIGRATION_URL")
    initialize_database(migration_url)
    with open_database(migration_url) as connection:
        seed_database(connection)


if __name__ == "__main__":
    initialize_database_from_environment()
    print("PostgreSQL schema and fixed route data initialized.")
